export const BASHKOHU_REGISTER_FORM_ACTIVE = () => ({
  type: "BASHKOHU_REGISTER_FORM_ACTIVE",
});

export const ADMIN_POSTO_NJOFTIM = () => ({
  type: "ADMIN_POSTO_NJOFTIM",
});

export const ADMIN_UPDATE_NJOFTIM = () => ({
  type: "ADMIN_UPDATE_NJOFTIM",
});

export const ADMIN_POSTO_POSTIM = () => ({
  type: "ADMIN_POSTO_POSTIM",
});

export const ADMIN_UPDATE_POSTIM = () => ({
  type: "ADMIN_UPDATE_POSTIM",
});
export const ADMIN_GET_REQUEST_NJOFTIMET = () => ({
  type: "ADMIN_GET_REQUEST_NJOFTIMET",
});

export const NJOFTIM_HAP_UPDATE = (data) => ({
  type: "NJOFTIM_HAP_UPDATE",
  payload: data,
});

export const MENU_HAP_TELEFON = () => ({
  type: "MENU_HAP_TELEFON",
});
export const MENU_MBYLL_TELEFON = () => ({
  type: "MENU_MBYLL_TELEFON",
});

export const MENU_STATIK_TELEFON = () => ({
  type: "MENU_STATIK_TELEFON",
});
export const SET_REGISTER_FORM_ANTAR_FOR_UPDATE = (data) => ({
  type: "SET_REGISTER_FORM_ANTAR_FOR_UPDATE",
  payload: data,
});
export const REGISTER_FORM_ACTIVE_UPDATE = () => ({
  type: "REGISTER_FORM_ACTIVE_UPDATE",
});
export const POSTIME_UPDATE_ACTIVE = () => ({
  type: "POSTIME_UPDATE_ACTIVE",
});

export const REGISTER_NJOFTIME_FORM = () => ({
  type: "REGISTER_NJOFTIME_FORM",
});
export const POSTIME_UPDATE_POST = (data) => ({
  type: "POSTIME_UPDATE_POST",
  payload: data,
});

export const REGISTER_NOFTIM_PJESTAR = (data) => ({
  type: "REGISTER_NOFTIM_PJESTAR",
  payload: data,
});
export const FETCH_NJOFTIME_REQUEST = "FETCH_NJOFTIME_REQUEST";
export const FETCH_NJOFTIME_SUCCESS = "FETCH_NJOFTIME_SUCCESS";
export const FETCH_NJOFTIME_FAILURE = "FETCH_NJOFTIME_FAILURE";

export const POST_NJOFTIME_REQUEST = "POST_NJOFTIME_REQUEST";
export const POST_NJOFTIME_SUCCESS = "POST_NJOFTIME_SUCCESS";
export const POST_NJOFTIME_FAILURE = "POST_NJOFTIME_FAILURE";

export const DELETE_NJOFTIME_REQUEST = "DETELE_NJOFTIME_REQUEST";
export const DELETE_NJOFTIME_SUCCESS = "DELETE_NJOFTIME_SUCCESS";
export const DELETE_NJOFTIME_FAILURE = "DELETE_NJOFTIME_FAILURE";

export const UPDATE_NJOFTIME_REQUEST = "UPDATE_NJOFTIME_REQUEST";
export const UPDATE_NJOFTIME_SUCCESS = "UPDATE_NJOFTIME_SUCCESS";
export const UPDATE_NJOFTIME_FAILURE = "UPDATE_NJOFTIME_FALIURE";

export const POST_ANTARET_VISITOR_REQUEST = "POST_ANTARET_VISITOR_REQUEST";
export const POST_ANTARET_VISITOR_SUCCESS = "POST_ANTARET_VISITOR_SUCCESS";
export const POST_ANTARET_VISITOR_FAILURE = "POST_ANTARET_VISITOR_FAILURE";

export const FETCH_ANTARET_ADMIN_REQUEST = "FETCH_ANTARET_ADMIN_REQUEST";
export const FETCH_ANTARET_ADMIN_SUCCESS = "FETCH_ANTARET_ADMIN_SUCCESS";
export const FETCH_ANTARET_ADMIN_FAILURE = "FETCH_ANTARET_ADMIN_FAILURE";

export const DELETE_ANTARET_REQUEST = "DELETE_ANTARET_REQUEST";
export const DELETE_ANTARET_SUCCESS = "DELETE_ANTARET_SUCCESS";
export const DELETE_ANTARET_FAILURE = "DELETE_ANTARET_FAILURE";

export const UPDATE_ANTARET_REQUEST = "UPDATE_ANTARET_REQUEST";
export const UPDATE_ANTARET_SUCCESS = "UPDATE_ANTARET_SUCCESS";
export const UPDATE_ANTARET_FAILURE = "UPDATE_ANTARET_FAILURE";

export const POST_POSTIME_REQUEST = "POST_POSTIME_REQUEST";
export const POST_POSTIME_SUCCESS = "POST_POSTIME_SUCCESS";
export const POST_POSTIME_FAILURE = "POST_POSTIME_FAILURE";

export const FETCH_POSTIME_REQUEST = "FETCH_POSTIME_REQUEST";
export const FETCH_POSTIME_SUCCESS = "FETCH_POSTIME_SUCCESS";
export const FETCH_POSTIME_FAILURE = "FETCH_POSTIME_FAILURE";

export const UPDATE_POSTIMET_REQUEST = "UPDATE_POSTIMET_REQUEST";
export const UPDATE_POSTIMET_SUCCESS = "UPDATE_POSTIMET_SUCCESS";
export const UPDATE_POSTIMET_FAILURE = "UPDATE_POSTIMET_FAILURE";

export const DELETE_POSTIMET_REQUEST = "DELETE_POSTIMET_REQUEST";
export const DELETE_POSTIMET_SUCCESS = "DELETE_POSTIMET_SUCCESS";
export const DELETE_POSTIMET_FAILURE = "DELETE_POSTIMET_FAILURE";

export const SEND_PJESMARRESIT_REQUEST = "SEND_PJESMARRESIT_REQUEST";
export const SEND_PJESMARRESIT_SUCCESS = "SEND_PJESMARRESIT_SUCCESS";
export const SEND_PJESMARRESIT_FAILURE = "SEND_PJESMARRESIT_FAILURE";

export const FETCH_NJOFTIMET_VISITORS_REQUEST =
  "FETCH_NJOFTIMET_VISITORS_REQUEST";
export const FETCH_NJOFTIMET_VISITORS_SUCCESS =
  "FETCH_NJOFTIMET_VISITORS_SUCCESS";
export const FETCH_NJOFTIMET_VISITORS_FAILURE =
  "FETCH_NJOFTIMET_VISITORS_FAILURE";

export const FETCH_POSTS_VISITOR_SUCCESS = "FETCH_POSTS_VISITOR_SUCCESS";
export const FETCH_POSTS_VISITOR_FAILURE = "FETCH_POSTS_VISITOR_FAILURE";
export const FETCH_POSTS_VISITOR_REQUEST = "const FETCH_POSTS_VISITOR_REQUEST";

export const FETCH_POSTIM_VISITOR_SUCCESS = "FETCH_POSTIM_VISITOR_SUCCESS";
export const FETCH_POSTIM_VISITOR_FAILURE = "FETCH_POSTIM_VISITOR_FAILURE";
export const FETCH_POSTIM_VISITOR_REQUEST = "FETCH_POSTIM_VISITOR_SUCCESS";
export const fetchDataRequest = (actiontype) => ({
  type: actiontype,
});

export const fetchDataSuccess = (data, actiontype) => ({
  type: actiontype,
  payload: data,
});

export const fetchDataFailure = (error, actiontype) => ({
  type: actiontype,
  payload: error,
});
